### ISSUE TITLE
The log constantly spams

### ISSUE THREAD

**Issue by matthew57778** [pedro2555/gta-iv-mods#2]
Tick: Object reference not set to an instance of an object.
[ultimate-overtaking-fix.log](https://github.com/pedro2555/gta-iv-mods/files/3364857/ultimate-overtaking-fix.log)

**Comment by pedro2555** [comment]
In what situation does this happen? Does the script work at all?

**Comment by matthew57778** [comment]
it occurs whenever i stop infront of a npc car and wait for a few but the
script does workishly

**Comment by pedro2555** [comment]
Ok, there seems to be no course of action. If the script does not work as intended please take the time to explain why, what happens and what you expected to happen.

The log file is not part of the script itself, and is merely a debugging helper, you should not be looking at it and assuming problems.

Hope the script works for you, enjoy. Feel free to open a new issue if you find any problem.
